### ISSUE TITLE
example using VideoTexture from live feed camera 

### ISSUE THREAD

**Issue by RansomBroker** [Knightro63/three_js#10]
i have facing problem E/flutter (  983): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: Class 'VideoTexture' has no instance method '[]'.

when pass camera to VideoTexture from flutter

**Comment by Knightro63** [comment]
HI @RansomBroker,

There is currently a bug with VideoTexture. I have resolved it but have not pushed to pub.dev because of other things that are being worked on as well. 

Please use CanvasTexture as a workaround for the moment. [Here](https://github.com/Knightro63/three_js/blob/main/examples/lib/material/webgl_materials_video_webcam.dart) is an example of how to do that. 

Hope this helps.

**Comment by RansomBroker** [comment]
![Screenshot from 2024-09-13 01-11-19](https://github.com/user-attachments/assets/4309fd6b-5e50-4391-a721-243a1c10d507)

when i use that code example the image show like that

**Comment by Knightro63** [comment]
Hi @RansomBroker,

I am sorry for the issue. This is the only way currently to use the video feed. 

What platform are you using?

I just tested it on Mac and it works fine, but I have not tested it on Android or web. 

There is currently an issue with windows and camera feeds. I will work on it soon.

Sorry for the issue. I hope to resolve it soon.

**Comment by RansomBroker** [comment]
yeah im testing it on android and desktop

**Comment by RansomBroker** [comment]
are video texture will release in near future? or webcam update for that issues on android and web?

**Comment by Knightro63** [comment]
Hi @RansomBroker,

I have updated the examples to fix the issue you are having with the android and web camera versions. 

Hope this helps.

**Comment by Knightro63** [comment]
Hi @RansomBroker,

I think we should be able to close this issue.
