### ISSUE TITLE
Android follows the example without any error, but with a black screen

### ISSUE THREAD

**Issue by vincentChen02** [Knightro63/three_js#14]
Android follows the example without any error, but with a black screen.
Adjusting the intensity of the light source has no effect.
Adjusting the camera Angle has no effect.
addAnimationEvent updates normally.
Adding a simple cube won't display either.

**Comment by vivagelive** [comment]
Hi! @vincentChen02 
Could you provide more information about issue? What kind of device (emulator or real device) did you use  and which example did you run?

**Comment by vincentChen02** [comment]
Hi! Running on the emulator and Run the contents of the repository under the example folder as shown in the figure
![Snipaste](https://github.com/user-attachments/assets/0575dfa0-6dbe-4563-bb44-9ea88754adfd)
![image](https://github.com/user-attachments/assets/f4d9d5ef-76c2-40f4-97de-6235808a4384)

**Comment by Knightro63** [comment]
Hi @vincentChen02,

I am sorry to hear you are having an issue. I have tried to replicate your issue but have not had success.

What version of android studio are you using and what version of emulator are you running?

This specific example needs more than 2048 MB of storage to run since the files are larger than that. Be sure to make the memory larger than 5500 MB for the virtual device.

Could you please run `flutter doctor`, `flutter clean`, and `flutter pub cache clean`. 

Hopefully one of these things solves the issue.

Also did it run on the rest of your platforms? e.g.(windows, macOS, iOS, web)

**Comment by vincentChen02** [comment]
Hi!@Knightro63
The version used is Android Studio Giraffe | 2022.3.1 Patch 3.

Testing the web and windows is fine,And using a Huawei real machine is no problem, I guess there is a problem with my simulator environment, I will test again, thank you very much for your answer.

There is another problem if you have time to help answer, I use the example of 'coin.glb' for cloning without problems, but cloning 'dash.glb', the display will be wrong, the model is incomplete, and I try to clone another glb file with more than 1M will have the same problem, is it because the file is too big to clone?
![Snipaste2](https://github.com/user-attachments/assets/291f04a5-d81b-4029-8d51-8fdb0d52da4a)
![Snipaste1](https://github.com/user-attachments/assets/f98984cb-f1e5-414b-a155-0c5eb5ce156b)
