### ISSUE TITLE
GLB Model Crashes App

### ISSUE THREAD

**Issue by Kvsh-03** [Knightro63/three_js#8]
I'm facing a big issue when loading models into flutter. My gpu consistently hits 100% and then crashes the app and returns a message in the terminal stating "Lost connection to the device". My gpu is quite old and I assume this might not consistently happen on the app release build, but is there anything I'm missing that fixes this?

**Comment by Knightro63** [comment]
Hi @Kvsh-03,

I am sorry to hear you are having an issue. I have experienced this with an older version of an ipad. If your files are too large and you don't have enough GPU memory this will occur. 

There is also a small memory deallocation issue if you go in and out of the builder constantly it will cause your memory to continue to go up.

You could reduce your model, or break it into multiple parts and load them separately. This is how this issue is usually solved for mobile games. This has also been an ongoing problem with three.js for web in the past due to this constraint. 

If you have any recommendations on other ways to help solve the issue I am more than happy to help.

Sorry for the inconvenience

**Comment by Knightro63** [comment]
Hi @Kvsh-03,

I hope all is well. 

I will be closing this issue soon unless you have another issue related to this?
